#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/opera.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/opera-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/opera-pa.desktop
