#!/bin/bash

## Desktop and icons install ##
echo "Adding icon"
mkdir -p $HOME/.local/share/icons/hicolor/scalable/apps/
cp \
  /opt/eclipse/plugins/org.eclipse.platform_*/eclipse128.png \
  $HOME/.local/share/icons/hicolor/scalable/apps/eclipsejava.png
echo "Adding start menu entry"
mkdir -p $HOME/.local/share/applications/
cp \
  /usr/share/applications/eclipsejava-pa.desktop \
  $HOME/.local/share/applications/
echo "Adding desktop shortcut"
mkdir -p $HOME/Desktop
cp \
  /usr/share/applications/eclipsejava-pa.desktop \
  $HOME/Desktop/
chmod +x $HOME/Desktop/eclipsejava-pa.desktop
