#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/eclipsejava.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/eclipsejava-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/eclipsejava-pa.desktop
