#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/freetube.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/freetube-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/freetube-pa.desktop
