#!/bin/bash

## Desktop and icons install ##
echo "Adding icon"
mkdir -p $HOME/.local/share/icons/hicolor/scalable/apps/
cp \
  /usr/share/icons/hicolor/symbolic/apps/com.amazon.workspacesclient-symbolic.svg \
  $HOME/.local/share/icons/hicolor/scalable/apps/com.amazon.workspacesclient.svg
echo "Adding start menu entry"
mkdir -p $HOME/.local/share/applications/
cp \
  /usr/share/applications/aws-workspaces-pa.desktop \
  $HOME/.local/share/applications/
echo "Adding desktop shortcut"
mkdir -p $HOME/Desktop
cp \
  /usr/share/applications/aws-workspaces-pa.desktop \
  $HOME/Desktop/
chmod +x $HOME/Desktop/aws-workspaces-pa.desktop
