#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/gimp.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/gimp-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/gimp-pa.desktop
