#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/kdenlive.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/kdenlive-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/kdenlive-pa.desktop
