FROM alpine:3.23 AS rootfs

ARG REPO
ARG SELKIES_VERSION=v2.0.0rc0

# Install packages
RUN \
  echo "**** install packages ****" && \
  apk add --no-cache --upgrade --virtual=build-dependencies \
    desktop-file-utils && \
  apk add --no-cache \
    bash \
    curl \
    dbus-x11 \
    font-noto \
    gcc \
    jq \
    lang \
    linux-headers \
    make \
    mesa-dri-gallium \
    mesa-gles \
    mesa-va-gallium \
    mesa-vulkan-ati \
    mesa-vulkan-layers \
    mesa-vulkan-swrast \
    musl-dev \
    netcat-openbsd \
    pulseaudio \
    xdg-utils \
    xf86-video-amdgpu \
    xf86-video-ati \
    $(if [ $(uname -m) = "x86_64" ];then echo "xf86-video-intel mesa-vulkan-intel";fi) \
    $(if [ $(uname -m) = "aarch64" ];then echo "mesa-vulkan-broadcom mesa-vulkan-panfrost mesa-vulkan-freedreno";fi) && \
  echo "**** setup xdg-open tunnel ****" && \
  mkdir -p /usr/share/applications && \
  curl -o \
    /usr/share/applications/xdg-open.desktop -L \
    "https://raw.githubusercontent.com/${REPO}/bins/xdg-open/xdg-open.desktop" && \
  curl -o \
    /usr/bin/xdg-open -L \
    "https://raw.githubusercontent.com/${REPO}/bins/xdg-open/xdg-open" && \
  chmod +x /usr/bin/xdg-open && \
  update-desktop-database && \
  echo "**** install selkies interposer ****" && \
  mkdir -p /tmp/selkies && \
  curl -o \
    /tmp/selkies.tar.gz -L \
    "https://github.com/selkies-project/selkies/archive/refs/tags/${SELKIES_VERSION}.tar.gz" && \
  tar xf \
    /tmp/selkies.tar.gz -C \
    /tmp/selkies --strip-components=1 && \
  cd /tmp/selkies/addons/js-interposer && \
  gcc -shared -fPIC -ldl \
    -o selkies_joystick_interposer.so \
    joystick_interposer.c && \
  mv \
    selkies_joystick_interposer.so \
    /usr/lib/selkies_joystick_interposer.so && \
  echo "**** install selkies fake udev ****" && \
  cd ../fake-udev && \
  make && \
  mkdir /opt/lib && \
  mv \
    libudev.so.1.0.0-fake \
    /opt/lib/ && \
  echo "**** install selkies webcam interposer ****" && \
  cd /tmp/selkies/addons/v4l2-interposer && \
  gcc -shared -fPIC -ldl -pthread \
    -o selkies_v4l2_interposer.so \
    v4l2_interposer.c && \
  mv \
    selkies_v4l2_interposer.so \
    /usr/lib/selkies_v4l2_interposer.so && \
  echo "**** cleanup ****" && \
  apk del --purge \
    build-dependencies && \
  rm -rf \
    /tmp/*
