FROM debian:trixie-slim AS rootfs

ARG REPO
ARG SELKIES_VERSION=v2.0.0rc0

# Install packages
RUN \
  echo "**** enable locales ****" && \
  sed -i \
    '/locale/d' \
    /etc/dpkg/dpkg.cfg.d/docker && \
  echo "**** install packages ****" && \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    dbus-x11 \
    desktop-file-utils \
    fonts-noto \
    gcc \
    jq \
    libc6-dev \
    libvulkan1 \
    locales-all \
    make \
    mesa-va-drivers \
    mesa-vulkan-drivers \
    netcat-openbsd \
    pulseaudio \
    xdg-utils \
    xserver-xorg-video-amdgpu \
    xserver-xorg-video-ati \
    $(if [ $(uname -m) = "x86_64" ];then echo "xserver-xorg-video-intel";fi) && \
  echo "**** setup xdg-open tunnel ****" && \
  mkdir -p /usr/share/applications && \
  curl -o \
    /usr/share/applications/xdg-open.desktop -L \
    "https://raw.githubusercontent.com/${REPO}/bins/xdg-open/xdg-open.desktop" && \
  curl -o \
    /usr/bin/xdg-open -L \
    "https://raw.githubusercontent.com/${REPO}/bins/xdg-open/xdg-open" && \
  chmod +x /usr/bin/xdg-open && \
  update-desktop-database && \
  echo "**** install selkies interposer ****" && \
  mkdir -p /tmp/selkies && \
  curl -o \
    /tmp/selkies.tar.gz -L \
    "https://github.com/selkies-project/selkies/archive/refs/tags/${SELKIES_VERSION}.tar.gz" && \
  tar xf \
    /tmp/selkies.tar.gz -C \
    /tmp/selkies --strip-components=1 && \
  cd /tmp/selkies/addons/js-interposer && \
  gcc -shared -fPIC -ldl \
    -o selkies_joystick_interposer.so \
    joystick_interposer.c && \
  mv \
    selkies_joystick_interposer.so \
    /usr/lib/selkies_joystick_interposer.so && \
  echo "**** install selkies fake udev ****" && \
  cd ../fake-udev && \
  make && \
  mkdir /opt/lib && \
  mv \
    libudev.so.1.0.0-fake \
    /opt/lib/ && \
  echo "**** install selkies webcam interposer ****" && \
  cd /tmp/selkies/addons/v4l2-interposer && \
  gcc -shared -fPIC -ldl -pthread \
    -o selkies_v4l2_interposer.so \
    v4l2_interposer.c && \
  mv \
    selkies_v4l2_interposer.so \
    /usr/lib/selkies_v4l2_interposer.so && \
  echo "**** cleanup ****" && \
  apt-get remove -y \
    desktop-file-utils && \
  apt-get autoclean && \
  rm -rf \
    /root/.cache \
    /var/lib/apt/lists/* \
    /var/tmp/* \
    /tmp/* && \
  echo "**** wrap dpkg for user installs ****" && \
  mv \
    /usr/bin/dpkg \
    /usr/bin/dpkg-real

# add local files
COPY /debian-root /
