#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/digikam.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/digikam-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/digikam-pa.desktop
