#!/bin/bash

## Desktop and icons install ##
for PHASE in Phase1 Phase2; do
  echo "Adding icon $PHASE"
  mkdir -p $HOME/.local/share/icons/hicolor/scalable/apps/
  cp \
    /usr/share/icons/io.github.freedoom.${PHASE}.png \
    $HOME/.local/share/icons/hicolor/scalable/apps/
  echo "Adding start menu entry $PHASE"
  mkdir -p $HOME/.local/share/applications/
  cp \
    /usr/share/applications/freedoom-${PHASE}-pa.desktop \
    $HOME/.local/share/applications/
  echo "Adding desktop shortcut $PHASE"
  mkdir -p $HOME/Desktop
  cp \
    /usr/share/applications/freedoom-${PHASE}-pa.desktop \
    $HOME/Desktop/
  chmod +x $HOME/Desktop/freedoom-${PHASE}-pa.desktop
done
