#!/bin/bash

## Desktop and icons install ##
for APP in freedoom1 freedoom2; do
  if [[ "${APP}" == "freedoom1" ]]; then
    PHASE=Phase1
  else
    PHASE=Phase2
  fi
  echo "Removing icon $APP"
  rm -f \
    $HOME/.local/share/icons/hicolor/scalable/apps/${APP}.png
  echo "Removing start menu entry $APP"
  rm -f \
    $HOME/.local/share/applications/freedoom-${PHASE}-pa.desktop
  echo "Removing desktop shortcut $APP"
  rm -f \
    $HOME/Desktop/freedoom-${PHASE}-pa.desktop
done
