#!/bin/bash

## Desktop and icons install ##
for PHASE in Phase1 Phase2; do
  echo "Removing icon $PHASE"
  rm -f \
    $HOME/.local/share/icons/hicolor/scalable/apps/io.github.freedoom.${PHASE}.png
  echo "Removing start menu entry $PHASE"
  rm -f \
    $HOME/.local/share/applications/freedoom-${PHASE}-pa.desktop
  echo "Removing desktop shortcut $PHASE"
  rm -f \
    $HOME/Desktop/freedoom-${PHASE}-pa.desktop
done
