#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/filezilla.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/filezilla-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/filezilla-pa.desktop
