#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/org.duckstation.DuckStation.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/duckstation-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/duckstation-pa.desktop
