#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/fr.handbrake.ghb.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/handbrake-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/handbrake-pa.desktop
