#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/org.azahar_emu.Azahar.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/azahar-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/azahar-pa.desktop
