#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/webcord.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/webcord-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/webcord-pa.desktop
