#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/anki.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/anki-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/anki-pa.desktop
