#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/ferdium.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/ferdium-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/ferdium-pa.desktop
