#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/librewolf.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/librewolf-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/librewolf-pa.desktop
