#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/geany.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/geany-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/geany-pa.desktop
