#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/gui-pa.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/gui-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/gui-pa.desktop
