#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/tabby.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/tabby-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/tabby-pa.desktop
