#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/net.kuribo64.melonDS.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/melonds-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/melonds-pa.desktop
