#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/onlyoffice-desktopeditors.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/onlyoffice-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/onlyoffice-pa.desktop
