#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/pycharm.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/pycharm-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/pycharm-pa.desktop
