#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/chatgpt.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/chatgpt-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/chatgpt-pa.desktop
