#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/kodi.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/kodi-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/kodi-pa.desktop
