#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/chromium.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/chromium-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/chromium-pa.desktop
