#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/keepassxc.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/keepassxc-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/keepassxc-pa.desktop
