#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/ppsspp.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/ppsspp-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/ppsspp-pa.desktop
