#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/obsidian.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/obsidian-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/obsidian-pa.desktop
