#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/org.dosbox_staging.dosbox_staging.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/dosbox-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/dosbox-pa.desktop
