#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/Nextcloud.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/nextcloud-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/nextcloud-pa.desktop
