#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/org.gnome.Weather.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/weather-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/weather-pa.desktop
