#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/org.freecadweb.FreeCAD.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/freecad-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/freecad-pa.desktop
