#!/bin/bash

## Desktop and icons install ##
echo "Adding icon"
mkdir -p $HOME/.local/share/icons/hicolor/scalable/apps/
cp \
  /opt/google/earth/pro/product_logo_256.png \
  $HOME/.local/share/icons/hicolor/scalable/apps/google-earth-pro.png
echo "Adding start menu entry"
mkdir -p $HOME/.local/share/applications/
cp \
  /usr/share/applications/earth-pa.desktop \
  $HOME/.local/share/applications/
echo "Adding desktop shortcut"
mkdir -p $HOME/Desktop
cp \
  /usr/share/applications/earth-pa.desktop \
  $HOME/Desktop/
chmod +x $HOME/Desktop/earth-pa.desktop
