#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/google-earth-pro.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/earth-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/earth-pa.desktop
