#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/winegui.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/winegui-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/winegui-pa.desktop