#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/wechat.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/wechat-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/wechat-pa.desktop
