#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/ai.storyteller.lightcraft.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/lightcraft-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/lightcraft-pa.desktop
