#!/bin/bash
for APP in et pdf wpp wps; do
  echo "Removing icon $APP"
  rm -f $HOME/.local/share/icons/hicolor/scalable/apps/wps-office2019-${APP}main.png
  echo "Removing start menu entry $APP"
  rm -f $HOME/.local/share/applications/wps-office-${APP}-pa.desktop
  echo "Removing desktop shortcut $APP"
  rm -f $HOME/Desktop/wps-office-${APP}-pa.desktop
done
