#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/parsecd.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/parsec-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/parsec-pa.desktop
