#!/bin/bash

## Desktop and icons install ##
echo "Adding icon"
mkdir -p $HOME/.local/share/icons/hicolor/scalable/apps/
cp \
  /opt/vivaldi/product_logo_256.png \
  $HOME/.local/share/icons/hicolor/scalable/apps/vivaldi.png
echo "Adding start menu entry"
mkdir -p $HOME/.local/share/applications/
cp \
  /usr/share/applications/vivaldi-pa.desktop \
  $HOME/.local/share/applications/
echo "Adding desktop shortcut"
mkdir -p $HOME/Desktop
cp \
  /usr/share/applications/vivaldi-pa.desktop \
  $HOME/Desktop/
chmod +x $HOME/Desktop/vivaldi-pa.desktop
