#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/vivaldi.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/vivaldi-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/vivaldi-pa.desktop
