#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/doublecmd.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/doublecmd-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/doublecmd-pa.desktop
