#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/retroarch.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/retroarch-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/retroarch-pa.desktop
