#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/flycast.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/flycast-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/flycast-pa.desktop
