#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/moonlight.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/moonlight-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/moonlight-pa.desktop
