#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/xenia_edge.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/xenia-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/xenia-pa.desktop
