#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/google-chrome.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/chrome-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/chrome-pa.desktop
