#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/Zoom.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/zoom-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/zoom-pa.desktop
