#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/ryujinx.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/ryujinx-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/ryujinx-pa.desktop
