#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/bitwarden.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/bitwarden-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/bitwarden-pa.desktop
