#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/vlc.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/vlc-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/vlc-pa.desktop
