#!/bin/bash

## Desktop and icons install ##
echo "Adding icon"
mkdir -p $HOME/.local/share/icons/hicolor/scalable/apps/
cp \
  /usr/share/icons/hicolor/scalable/apps/org.flameshot.Flameshot.svg \
  $HOME/.local/share/icons/hicolor/scalable/apps/
echo "Adding start menu entry"
mkdir -p $HOME/.local/share/applications/
cp \
  /usr/share/applications/flameshot-pa.desktop \
  $HOME/.local/share/applications/
echo "Adding desktop shortcut"
mkdir -p $HOME/Desktop
cp \
  /usr/share/applications/flameshot-pa.desktop \
  $HOME/Desktop/
chmod +x $HOME/Desktop/flameshot-pa.desktop

## Default config ##
FLAMESHOT_CONF=$HOME/.config/flameshot/flameshot.ini
if ! grep -q "^useX11LegacyScreenshot=" $FLAMESHOT_CONF 2>/dev/null; then
  echo "Setting X11 legacy screenshot"
  mkdir -p $HOME/.config/flameshot/
  if grep -q "^\[General\]" $FLAMESHOT_CONF 2>/dev/null; then
    sed -i '/^\[General\]/a useX11LegacyScreenshot=true' $FLAMESHOT_CONF
  else
    printf '[General]\nuseX11LegacyScreenshot=true\n' >> $FLAMESHOT_CONF
  fi
fi
