#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/org.flameshot.Flameshot.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/flameshot-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/flameshot-pa.desktop
