#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/telegram.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/telegram-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/telegram-pa.desktop
