#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/org.inkscape.Inkscape.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/inkscape-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/inkscape-pa.desktop
