#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/xemu.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/xemu-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/xemu-pa.desktop
