#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/qbittorrent.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/qbittorrent-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/qbittorrent-pa.desktop
