#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/thunderbird.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/thunderbird-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/thunderbird-pa.desktop
