#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/zen.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/zen-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/zen-pa.desktop
