#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/org.remmina.Remmina.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/remmina-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/remmina-pa.desktop
