#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/com.obsproject.Studio.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/obs-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/obs-pa.desktop
