#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/OrcaSlicer.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/orcaslicer-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/orcaslicer-pa.desktop
