#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/kicad.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/kicad-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/kicad-pa.desktop
