#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/rustdesk.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/rustdesk-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/rustdesk-pa.desktop
