#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/mame.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/mame-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/mame-pa.desktop
