#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/joplin.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/joplin-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/joplin-pa.desktop
