#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/freeciv-client.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/freeciv-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/freeciv-pa.desktop
