#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/org.shotcut.Shotcut.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/shotcut-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/shotcut-pa.desktop
