#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/firefox.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/firefox-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/firefox-pa.desktop
