#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/ai.storyteller.printcraft.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/printcraft-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/printcraft-pa.desktop
