#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/zim.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/zim-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/zim-pa.desktop
