#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/torbrowser.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/torbrowser-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/torbrowser-pa.desktop
