#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/de.haeckerfelix.Shortwave.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/shortwave-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/shortwave-pa.desktop
