#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/zotero.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/zotero-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/zotero-pa.desktop
