#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/logisim-evolution.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/logisim-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/logisim-pa.desktop
