#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/sqlitebrowser.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/sqlitebrowser-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/sqlitebrowser-pa.desktop
