#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/ai.opencode.desktop.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/opencode-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/opencode-pa.desktop
