#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/blender.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/blender-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/blender-pa.desktop
