#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/rpcs3.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/rpcs3-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/rpcs3-pa.desktop
