#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/spotube.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/spotube-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/spotube-pa.desktop
