#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/krita.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/krita-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/krita-pa.desktop
