#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/mumble.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/mumble-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/mumble-pa.desktop
