#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/franz.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/franz-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/franz-pa.desktop
