#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/ai.storyteller.photocraft.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/photocraft-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/photocraft-pa.desktop
