#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/idea.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/idea-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/idea-pa.desktop
