#!/bin/bash

## Desktop and icons install ##
echo "Adding icon"
mkdir -p $HOME/.local/share/icons/hicolor/scalable/apps/
cp \
  /usr/share/icons/hicolor/scalable/apps/info.cemu.Cemu.png \
  $HOME/.local/share/icons/hicolor/scalable/apps/
echo "Adding start menu entry"
mkdir -p $HOME/.local/share/applications/
cp \
  /usr/share/applications/cemu-pa.desktop \
  $HOME/.local/share/applications/
echo "Adding desktop shortcut"
mkdir -p $HOME/Desktop
cp \
  /usr/share/applications/cemu-pa.desktop \
  $HOME/Desktop/
chmod +x $HOME/Desktop/cemu-pa.desktop
