#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/info.cemu.Cemu.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/cemu-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/cemu-pa.desktop
