#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/yandex-browser.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/yandex-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/yandex-pa.desktop
