#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/unsloth-studio.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/unsloth-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/unsloth-pa.desktop
