#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/ai.storyteller.filmcraft.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/filmcraft-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/filmcraft-pa.desktop
