#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/org.gnome.Lollypop.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/lollypop-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/lollypop-pa.desktop
