#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/io.github.celluloid_player.Celluloid.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/celluloid-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/celluloid-pa.desktop
