# Focal is used here for broad compatibility
FROM ubuntu:focal

RUN \
  echo "**** install build deps ****" && \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    gawk \
    gcc \
    jq \
    libarchive-dev \
    libtalloc-dev \
    make && \
  echo "**** ingest proot src ****" && \
  mkdir /build && \
  curl -L \
    "https://github.com/linuxserver/proot/archive/master.tar.gz" \
    | tar -xzf - -C "/build" --strip-components=1 && \
  echo "**** build logic ****" && \
  echo "#!/bin/bash" > /entrypoint && \
  echo "LDFLAGS=\"\${LDFLAGS} -static\" make -C src proot GIT=false" >> /entrypoint && \
  echo "strip src/proot" >> /entrypoint && \
  echo "mv src/proot /mnt/" >> /entrypoint && \
  chmod +x /entrypoint && \
  echo "**** cleanup ****" && \
  apt-get autoremove && \
  apt-get clean && \
  rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/* \
    /var/log/*

WORKDIR /build

ENTRYPOINT ["/entrypoint"] 
