#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/lm-studio.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/lmstudio-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/lmstudio-pa.desktop
