#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/postman.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/postman-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/postman-pa.desktop
