#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/antigravity.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/antigravity-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/antigravity-pa.desktop
