#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/dreamm.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/dreamm-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/dreamm-pa.desktop
