#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/dolphin-emu.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/dolphin-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/dolphin-pa.desktop
