#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/net.shadps4.shadPS4.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/shadps4-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/shadps4-pa.desktop
