#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/signal-desktop.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/signal-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/signal-pa.desktop
