#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/calibre-gui.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/calibre-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/calibre-pa.desktop
