#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/helium.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/helium-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/helium-pa.desktop
