#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/ai.storyteller.effectcraft.svg
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/effectcraft-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/effectcraft-pa.desktop
