#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/claude-desktop.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/claude-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/claude-pa.desktop
